// <auto-generated />
namespace HKOWebMVC4.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Prilikomtestiranja : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Prilikomtestiranja));
        
        string IMigrationMetadata.Id
        {
            get { return "201605290958256_Prilikom testiranja"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
